# The config recipe.
# https://rasa.com/docs/rasa/model-configuration/
recipe: default.v1

# The assistant project unique identifier
# This default value must be replaced with a unique assistant name within your deployment
assistant_id: 20250312-090551-dark-frequency

# Configuration for Rasa NLU.
# https://rasa.com/docs/rasa/nlu/components/
language: en

pipeline:
- name: "SpacyNLP"
  model: "en_core_web_md"
- name: "WhitespaceTokenizer"
- name: "RegexFeaturizer"
- name: "CountVectorsFeaturizer"
- name: "DIETClassifier"
  epochs: 100
  batch_size: 8
- name: "EntitySynonymMapper"
- name: "ResponseSelector"
  epochs: 100


policies:
- name: "RulePolicy"
- name: "MemoizationPolicy"
- name: "TEDPolicy"



#version: "2.0"
#language: "en"
#pipeline:
#  - name: "SpacyNLP"
#    model: "en_core_web_md"
#  - name: "SpacyTokenizer"
#  - name: "DIETClassifier"
#    epochs: 100
#  - name: "EntitySynonymMapper"
#  - name: "ResponseSelector"
#    epochs: 100
#  - name: "FallbackClassifier"
#    threshold: 0.7
#    ambiguity_threshold: 0.1
#
#policies:
#  - name: "RulePolicy"
#  - name: "MemoizationPolicy"
#  - name: "TEDPolicy"
